# Sklearn

## sklearn.model_selection

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [7]:
from sklearn import model_selection, datasets


import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [8]:
iris = datasets.load_iris()

In [9]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [10]:
print iris

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

In [11]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [12]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [13]:
test_labels

array([1, 0, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 2,
       1, 0, 1, 1, 0, 1, 2, 0, 2, 0, 0, 1, 2, 0, 2, 2, 0, 1, 0, 0, 0, 1])

In [14]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 5.1  3.8  1.6  0.2]
 [ 5.5  2.4  3.7  1. ]
 [ 6.7  3.3  5.7  2.5]
 [ 6.3  2.7  4.9  1.8]
 [ 6.5  3.   5.8  2.2]]


Тестовая выборка:
[[ 6.7  3.1  4.4  1.4]
 [ 5.1  3.7  1.5  0.4]
 [ 7.7  2.8  6.7  2. ]
 [ 4.8  3.4  1.6  0.2]
 [ 5.   3.5  1.3  0.3]]


In [15]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[0 1 2 2 2 2 2 2 0 0 2 2 2 0 2 0 1 1 0 1 0 0 0 1 0 0 2 2 2 0 2 0 1 2 0 2 0
 1 1 2 2 1 1 1 1 0 2 1 2 2 0 2 0 0 1 2 1 1 0 0 0 1 2 1 2 2 2 0 1 2 2 1 1 2
 2 0 1 0 1 2 2 1 1 0 0 0 1 0 0 0 1 0 1 1 1 1 1 0 2 1 1 0 2 0 2]


Метки классов на тестовой выборке:
[1 0 2 0 0 2 1 1 2 1 1 1 0 1 2 2 2 1 0 1 2 2 2 1 0 1 1 0 1 2 0 2 0 0 1 2 0
 2 2 0 1 0 0 0 1]


### Стратегии проведения кросс-валидации

In [16]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,40)

#### KFold

In [17]:
kf = model_selection.KFold(n_splits = 5)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [18]:
kf = model_selection.KFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[1 2 5 6 7] [0 3 4 8 9]
[0 3 4 8 9] [1 2 5 6 7]


In [19]:
kf = model_selection.KFold(n_splits = 2, shuffle = True, random_state = 1)
for train_indices, test_indices in kf.split(X):
    print train_indices, test_indices

[1 3 5 7 8] [0 2 4 6 9]
[0 2 4 6 9] [1 3 5 7 8]


#### StratifiedKFold

In [20]:
y = np.array([0] * 5 + [1] * 5)
print y

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True, random_state = 0)
for train_indices, test_indices in skf.split(X, y):
    print train_indices, test_indices

[0 0 0 0 0 1 1 1 1 1]
[3 4 8 9] [0 1 2 5 6 7]
[0 1 2 5 6 7] [3 4 8 9]


In [21]:
target = np.array([0, 1] * 5)
print target

skf = model_selection.StratifiedKFold(n_splits = 2,shuffle = True)
for train_indices, test_indices in skf.split(X, target):
    print train_indices, test_indices

[0 1 0 1 0 1 0 1 0 1]
[0 1 4 5] [2 3 6 7 8 9]
[2 3 6 7 8 9] [0 1 4 5]


#### ShuffleSplit

In [22]:
ss = model_selection.ShuffleSplit(n_splits = 10, test_size = 0.2)

for train_indices, test_indices in ss.split(X):
    print train_indices, test_indices

[4 8 2 0 6 3 7 9] [1 5]
[7 3 1 4 6 0 5 9] [8 2]
[2 7 6 3 9 4 0 1] [5 8]
[2 7 1 9 0 6 4 8] [5 3]
[0 4 8 6 5 1 3 2] [7 9]
[4 2 1 7 3 8 5 9] [0 6]
[3 2 1 6 5 8 9 4] [7 0]
[8 0 2 7 9 4 1 5] [6 3]
[2 7 0 1 9 3 4 6] [5 8]
[9 8 1 2 6 0 5 7] [3 4]


#### StratifiedShuffleSplit

In [28]:
target = np.array([0] *0 + [1] * 20)
print target

sss = model_selection.StratifiedShuffleSplit(test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print train_indices, test_indices

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


ValueError: Found input variables with inconsistent numbers of samples: [10, 40]

#### Leave-One-Out

In [24]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print train_indices, test_index

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators